project:
  type: book
  output-dir: docs

book:
  title: "老景心态"
  author: "Norah Jones"
  date: "3/1/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - quar1.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - united
      - brand
  pdf:
    documentclass: scrreprt



