# 究竟是什么，让别人喜欢你？

## 究竟是什么，让别人喜欢你？

咱们进入第三课，这课的内容叫做什么呢？《究竟是什么，让别人喜欢你》，也就是说我们解决**魅力**这个问题。咱们进入这套心态课程以后呢，我们最开始讲的是这个世界的底层逻辑，底层逻辑讲清楚以后，我们分两步走，第一步讲我们**与人的关系**，只要在这个世界上我们解决了与人的关系，让所有人跟我接触之后绝大部分都会喜欢我这个人。有了这个，我们全都有了。这个是底层逻辑。有好事所有人惦记着我，我们心仪的异性她能爱上我，有了这个，我们的人生全有了。那么究竟是什么东西导致了别人会喜欢我们呢？有人会说，有钱。为什么我以前没人看得起我？大家都不喜欢我，不就是因为我比较卑微，我没有钱，没有地位吗？那么以后我有了钱了，有了地位了，别人就尊重我了，喜欢我了，是这样吗？前面我讲过，<span style="color: rgb(255, 100, 100); font-weight: bold">我们做事情要揭开表面的迷雾看到更深层次的东西</span>。那么咱们就从这句话，有钱了，别人就喜欢我了，咱们就从这句话往下分析啊。

那么既然我们说有钱了，别人就喜欢我了。抓住这个基本上这个问题就解决了。那也就是说有钱这件事情在别人喜欢与不喜欢是决定因素，最关键点的因素。那咱们分析分析什么叫最关键点的因素，**最关键点的因素**是指你把一件最关键的这个东西拿到了，周边所有其他的东西，我有没有，大差不差，不太有所谓，不会有本质的影响，最多是个10%以内的影响，但总体上没事，这个叫最关键因素。比如说咱们举个例子，我们人都喜欢黄金，那这个东西到底是不是黄金是最关键因素。今天广场上发黄金，我去的早，抢回来一块一公斤重的，雕着花，很漂亮的，喷着香水，包装得很精美的一块大金锭子。喜欢吗？非常喜欢，非常开心。那明天我去晚了，没抢到这么好的，我抢到一块跟石头一样，长得很难看的，上面还沾着很多肮脏的东西，拿手都不敢拿，只能拿破报纸包一下，拿塑料袋，拎着鼻子，捏着鼻子，我拿回来。那你就不喜欢它了吗？不会的。没有本质的区别。所以，**它是不是黄金，就是你喜欢不喜欢它的最决定因素，这是最决定因素**。那我们来看一看，“我有钱了“这件事情是不是别人喜欢我的最关键因素？

比如说我老景原来没有钱，大家都瞧不起我，不喜欢我。然后我就奋发图强，经过十年的努力，每天起早贪黑，五点钟起床，努力了整整十年，我终于有钱了，我有工厂，有几个亿的资产，我的一辆车都几百万，还有好几辆，还有别墅，一块手表都几百万块钱，哎，别人就喜欢我了。那么好，现在我参加一个聚会，主持人来介绍，说大家认识啊，这是老景，著名企业家景某某，就是他，他怎么怎么样，白手起家，起早贪黑，现在创造一个商业帝国，等等等等等等。他非常厉害，你别看他很低调，他一块手表就几百万，他今天开的车，他最差的车都两百多万，等等等等，说一大堆，你们认识认识吧。这时候聚会的朋友对老景这个人还是有好印象。就，哎，不错，这个人挺优秀。好像管用，对吗？

换一种方式，老景去参加这个聚会，自己来介绍自己，用一种吹牛的方式来介绍。兄弟们，我自我介绍一下，你们知道我是谁吗？我是景某某。著名企业家景某某就是我。你们知道我原来多么多么不行，我起早贪黑怎么怎么样，我现在商业帝国，你们知道我那个工厂就吃多少个亿，我今天随随便便开一辆车，我最便宜的车都两百多万，你们开的起吗？我告诉你，男人就得有钱，这一块表，你别看很低调，实际上它值几百万，等等等等。你们跟我学着点吧。这么一番话介绍出去以后，你们还会喜欢我吗？你们不讨厌我，已经是很有涵养了。怎么解释？怎么我十年的努力，变成有钱了，被这一分钟的自我介绍就干没了，干光光了。如果是另外一种环境呢？比如相亲这种环境。这个女生从其他渠道得知我这种经历。她是有好感的。如果我跟她吹，结果呢？烦我还来不及呢。她承认，你有钱是很厉害。但那又怎么样？你人不行，所以我们敲开脑壳，好好想一想吧。别这些真实的现实世界都摆在面前，我们都不承认。

**我所有课程里面讲的内容都会非常颠覆我们大脑，可能会造成我们情绪的抵触。**但是你静下心来想一想，是不是这样一种客观实际的情况。**你要想改变你的结果，必须得改这（大脑）。这个维度不改变，你改不了自己的生活和结果。**十年的努力居然抵不过一分钟的吹牛式的自我介绍，这还不值得我们惊醒吗？究竟是有钱这件事情带来喜欢还是别的呢？我们好好想一想，咱们换一种方式，不是关键因素吗？现在，有钱这件事情不是别人喜欢不喜欢你的关键因素了。因为关键因素的定义是有了它大差不差了，现在我有了它了，怎么一分钟自我介绍把它给干没了呢？那它还是关键因素吗？那什么是关键因素？我换一种方式。我老景这个人性格非常的低调，，很温和，照顾好身边的每一个人，很有安全感。这样一种性格，同时我很有钱，你们会喜欢我吗？会喜欢我。我没有攻击性，对你都很好很好，而且又低调。同时我很有钱，你们一定会喜欢我这个人的，那现在，突然有一天我破产了，我没钱了，我甚至得骑自行车上班了，但是我的性格不变，还是很低调，对大家很好，很温和，很有安全感，你们难道因为我没钱就不喜欢我了吗？这个才是别人喜欢不喜欢你的关键决定因素，抓到了这种性格，你有没有钱，不影响别人喜欢你不喜欢你。我们敲开脑壳，好好想一想吧，震撼一下自己的大脑吧，提升一下自己的思维逻辑吧。究竟什么东西是造成别人喜欢与不喜欢的关键决定性因素，不要老抓那些外围的。我告诉你，“有钱”只是一个周边因素。甚至长得漂亮不漂亮，身材好不好，帅气不帅气，学历高不高等等，这些东西都不是决定性的因素。你看那些你都有了，但是你性格很差，别人不喜欢你。你性格很好，别人是喜欢你的。但是为什么我说有钱啊，怎么怎么的，那些外围的就能够别人喜欢呢？是因为这些外围的带来了你的一些性格上的改变。好好想想这个问题。我们敲开脑壳好好想一想。究竟是那些外在的东西，金钱啊，地位啊，漂亮啊等等，那个导致了别人喜欢你这个人，还是你这个人导致了别人喜欢你。是人还是这些外在的事？你想一想。有钱别人就喜欢我了，也不是不对，但它是间接的。因为有了钱之后，外在的有钱、有地位等等，包括漂亮啊，包括等等这些诸多的因素，它会带来我们有底气，带来我自信又强大，那么这种自信强大的这种外在表现，它就会让别人喜欢。


[我的分析](intro.qmd)